In [2]:
import pandas as pd

Season 2024-2025

In [3]:
df_scenarios = pd.read_parquet("../../../input_data/SMH_trajectories_FluRound1_2024_2025.parquet")

In [4]:
df_scenarios.head()

,origin_date,scenario_id,location,target,horizon,age_group,output_type,output_type_id,value,run_grouping,stochastic_run,model_id,traj_id,target_end_date
0,2024-08-11,B-2024-08-01,06,inc hosp,1.0,0-130,sample,None,0.0,2.0,101,CADPH-FluCAT,CADPH-FluCAT-B-2024-08-01-101-2.0,2024-08-17
1,2024-08-11,B-2024-08-01,06,inc hosp,2.0,0-130,sample,None,53.0,2.0,101,CADPH-FluCAT,CADPH-FluCAT-B-2024-08-01-101-2.0,2024-08-24
2,2024-08-11,B-2024-08-01,06,inc hosp,3.0,0-130,sample,None,85.0,2.0,101,CADPH-FluCAT,CADPH-FluCAT-B-2024-08-01-101-2.0,2024-08-31
3,2024-08-11,B-2024-08-01,06,inc hosp,4.0,0-130,sample,None,67.0,2.0,101,CADPH-FluCAT,CADPH-FluCAT-B-2024-08-01-101-2.0,2024-09-07
4,2024-08-11,B-2024-08-01,06,inc hosp,5.0,0-130,sample,None,64.0,2.0,101,CADPH-FluCAT,CADPH-FluCAT-B-2024-08-01-101-2.0,2024-09-14

In [18]:
for model in df_scenarios["model_id"].unique():
    df_model = df_scenarios[df_scenarios["model_id"] == model]
    print(f"Model: {model}")
    print(f"Number of country coverage: {df_model['location'].nunique()}")
    print(f"Locations: {', '.join(sorted(df_model['location'].unique()))}")

Model: CADPH-FluCAT
Number of country coverage: 1
Locations: 06
Model: NIH-Flu_TS
Number of country coverage: 39
Locations: 01, 04, 05, 06, 08, 09, 13, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 35, 36, 37, 39, 40, 42, 45, 46, 47, 48, 50, 51, 53, 54, 55, US
Model: USC-SIkJalpha
Number of country coverage: 57
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 60, 66, 69, 72, 78, US
Model: UVA-FluXSim
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: NotreDame-FRED
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: UT-ImmunoSEIRS
Number of country coverage: 51
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: MOBS_NEU-GLEAM_FLU
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: PSI-M2
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: UVA-EscapeFlu
Number of country coverage: 51
Locations: 01, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US

In [9]:
df_scenarios_23 = pd.read_parquet("../../../input_data/SMH_trajectories_FluRound1_2023_2024_states.parquet")
df_scenarios_23.head()

,Unnamed: 0,horizon,output_type_id,value,target,age_group,scenario_id,origin_date,location,output_type,model_name
0,23448,1.0,49.0,16.383140,inc hosp,0-130,A-2023-08-14,2023-09-03,US,sample,CDDEP-FluCompModel
1,23449,1.0,50.0,16.079721,inc hosp,0-130,A-2023-08-14,2023-09-03,US,sample,CDDEP-FluCompModel
2,23450,1.0,51.0,16.102788,inc hosp,0-130,A-2023-08-14,2023-09-03,US,sample,CDDEP-FluCompModel
3,23451,1.0,52.0,16.615713,inc hosp,0-130,A-2023-08-14,2023-09-03,US,sample,CDDEP-FluCompModel
4,23452,1.0,53.0,16.490636,inc hosp,0-130,A-2023-08-14,2023-09-03,US,sample,CDDEP-FluCompModel

In [17]:
for model in df_scenarios_23["model_name"].unique():
    df_model = df_scenarios_23[df_scenarios_23["model_name"] == model]
    print(f"Model: {model}")
    print(f"Number of country coverage: {df_model['location'].nunique()}")
    print(f"Locations: {', '.join(sorted(df_model['location'].unique()))}")

Model: CDDEP-FluCompModel
Number of country coverage: 1
Locations: US
Model: MOBS_NEU-GLEAM_FLU
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: NIH-FluD
Number of country coverage: 1
Locations: US
Model: NIH-Flu_TS
Number of country coverage: 13
Locations: 06, 08, 09, 13, 24, 26, 27, 35, 36, 39, 41, 47, US
Model: NotreDame-FRED
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: PSI-M2
Number of country coverage: 52
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: USC-SIkJalpha
Number of country coverage: 57
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 60, 66, 69, 72, 78, US
Model: UT-ImmunoSEIRS
Number of country coverage: 51
Locations: 01, 02, 04, 05, 06, 08, 09, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, US
Model: UVA-FluXSim
Number of country coverage: 1
Locations: US