In [1]:
import pandas as pd 
import numpy as np
import requests
from io import StringIO
from datetime import timedelta, datetime
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

/Users/stefania/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [ ]:
df_parquet =  pd.read_parquet("../../../../input_data/SMH_projections_age65plus.parquet")
df_parquet.model_name.unique()

array(['MOBS_NEU-GLEAM_FLU', 'NotreDame-FRED', 'USC-SIkJalpha',
       'UVA-FluXSim', 'UVA-EscapeFlu'], dtype=object)

In [25]:
def read_csv_from_github(url):
    """
    Reads a CSV file from a given GitHub URL and returns it as a pandas DataFrame.
    input:
        url = URL of the CSV file on GitHub
    output:
        df = DataFrame containing the CSV data
    """
    response = requests.get(url)
    if response.status_code == 200:
        csv_content = response.content.decode('utf-8')
        return pd.read_csv(StringIO(csv_content))
    else:
        print(f"Failed to fetch file. Status code: {response.status_code}, Message: {response.text}")
        return pd.DataFrame()
        
def loading_surveillance_eval(start_date, end_date, path_surv):
    """
    This function loads the surveillance data from a GitHub repository.
    input:
        start_date = start date for the data
        github_repo = GitHub repository name
        github_directory = directory in the GitHub repository
        surveillance_file = name of the surveillance file
        state = state to filter the data
        horizon_to_start = horizon to start the data
    output:
        df_surv_date_US = dataframe with the filtered surveillance data
    """
    df_surv = pd.read_csv(path_surv)

    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)
    df_surv['date'] = pd.to_datetime(df_surv['date'])
    df_surv = df_surv[(df_surv['target'] == 'inc hosp') & (df_surv['age_group'] == '65-130')]
    # filter the dataframe to only include rows where the location is 'US' and the date is between start_date and ref_date
    df_surv_date_US = df_surv[(df_surv.location == 'US') & 
                            (df_surv.date >= start_date) & 
                            (df_surv.date <= end_date)]
    df_surv_date_US = df_surv_date_US.rename(columns={"observation": "hospitalizations"})
    df_surv_date_US = df_surv_date_US.sort_values(by='date')
    df_surv_date_US['horizon'] = np.arange(1, len(df_surv_date_US)+1)
    return df_surv_date_US

In [ ]:
state = 'US'
# Loading surveillance data for evaluation: last surveillance file
start_date = datetime(2024, 11, 23)  # Adjusted to the latest date in the surveillance data
end_date = datetime(2025, 5, 17)
path_surv =  "../../../../input_data/target-data-age-stratification.csv"
df_surv = loading_surveillance_eval(start_date, end_date, path_surv)
df_surv

            date location  hospitalizations age_group    target  horizon
22725 2024-11-23       US            1572.0    65-130  inc hosp        1
22730 2024-11-30       US            2077.0    65-130  inc hosp        2
22735 2024-12-07       US            3122.0    65-130  inc hosp        3
22740 2024-12-14       US            4529.0    65-130  inc hosp        4
22745 2024-12-21       US            7556.0    65-130  inc hosp        5
22750 2024-12-28       US           14858.0    65-130  inc hosp        6
22755 2025-01-04       US           21984.0    65-130  inc hosp        7
22760 2025-01-11       US           17210.0    65-130  inc hosp        8
22765 2025-01-18       US           17547.0    65-130  inc hosp        9
22770 2025-01-25       US           21440.0    65-130  inc hosp       10
22775 2025-02-01       US           28006.0    65-130  inc hosp       11
22780 2025-02-08       US           30194.0    65-130  inc hosp       12
22785 2025-02-15       US           26070.0    65-130  inc hosp       13
22790 2025-02-22       US           22122.0    65-130  inc hosp       14
22795 2025-03-01       US           18115.0    65-130  inc hosp       15
22800 2025-03-08       US           13926.0    65-130  inc hosp       16
22805 2025-03-15       US           10519.0    65-130  inc hosp       17
22810 2025-03-22       US            7858.0    65-130  inc hosp       18
22815 2025-03-29       US            5265.0    65-130  inc hosp       19
22820 2025-04-05       US            3561.0    65-130  inc hosp       20
22825 2025-04-12       US            2457.0    65-130  inc hosp       21
22830 2025-04-19       US            1853.0    65-130  inc hosp       22
22835 2025-04-26       US            1527.0    65-130  inc hosp       23
22840 2025-05-03       US            1180.0    65-130  inc hosp       24
22845 2025-05-10       US             977.0    65-130  inc hosp       25
22850 2025-05-17       US             920.0    65-130  inc hosp       26

In [42]:
df_surv.tail(10)

            date location  hospitalizations age_group    target  horizon
22805 2025-03-15       US           10519.0    65-130  inc hosp       17
22810 2025-03-22       US            7858.0    65-130  inc hosp       18
22815 2025-03-29       US            5265.0    65-130  inc hosp       19
22820 2025-04-05       US            3561.0    65-130  inc hosp       20
22825 2025-04-12       US            2457.0    65-130  inc hosp       21
22830 2025-04-19       US            1853.0    65-130  inc hosp       22
22835 2025-04-26       US            1527.0    65-130  inc hosp       23
22840 2025-05-03       US            1180.0    65-130  inc hosp       24
22845 2025-05-10       US             977.0    65-130  inc hosp       25
22850 2025-05-17       US             920.0    65-130  inc hosp       26

In [ ]:
loss_function = 'wmape'
season = "2024-2025"
df_original_ensemble = pd.read_csv(f'../../output_data/original_ensembles_agestrata/Ensemble_Ens2_USnational.csv', index_col = 0)
df_original_ensemble

     quantile       value  horizon
1       0.010   20.030710        1
2       0.025   36.161075        1
3       0.050   42.876155        1
4       0.100   48.595233        1
5       0.150   52.356198        1
..        ...         ...      ...
709     0.850  477.900000       31
710     0.900  507.800000       31
711     0.950  549.400000       31
712     0.975  587.710000       31
713     0.990  622.841000       31

[713 rows x 3 columns]

In [44]:
def import_ensemble_original(df, df_surv, date_ref):
    df_surv['date'] = pd.to_datetime(df_surv['date'])
    valid_horizons = df_surv['horizon'].unique()
    df = df[df['horizon'].isin(valid_horizons)]
    # Map each horizon to its corresponding date
    horizon_to_date = df_surv.set_index('horizon')['date'].to_dict()
    df['date'] = df['horizon'].map(horizon_to_date)
    # Filter to only include dates after or equal to date_only
    date_ref = pd.to_datetime(date_ref)
    df = df[df['date'] >= date_ref]
    # Merge in hospitalization targets
    df = df.merge(df_surv[['date', 'hospitalizations']].drop_duplicates(), on='date', how='left')
    return df

def import_ensemble2(file_path, surv_lookup, horizon_to_date):
    df = pd.read_csv(file_path, index_col=0)
    df['horizon'] = df['horizon'].astype(int)
    df['date'] = df['horizon'].map(horizon_to_date)
    df['date'] = pd.to_datetime(df['date'])
    return df.merge(surv_lookup, on='date', how='left')

In [45]:
def get_perc_error(actual, sim, last=4): 
    return 100 * np.mean(np.abs(actual[-last:] - sim[-last:]) / actual[-last:])

def get_wmape(actual, sim) -> float:
    return np.sum(np.abs(actual - sim)) / np.sum(np.abs(actual))

def diff(a, b, norm=False): 
    if norm:
        if a != 0:
            return (a - b) / a
        else: 
            return 0
    else:
        return (a - b)

def interval_score(y, u, l, alpha, norm=False): 
    return -diff(l, u, norm=norm) + 2 / alpha * -diff(y, l, norm=norm) * (y < l) + 2 / alpha * diff(y, u, norm=norm) * (y > u)
    

def weighted_interval_score(y, u_s, l_s, m, alpha_ks, w0=1./2., norm=False):
    K = len(alpha_ks)
    wks = np.array(alpha_ks) / 2.
    return 1. / (K + 1./2.) * (w0 * np.abs(diff(y, m, norm=norm)) + np.dot(wks, [interval_score(y, u, l, a_k, norm=norm) for u, l, a_k in zip(u_s, l_s, alpha_ks)]))


def get_upper_bound(sim_stats, alpha, idx): 
    # get upper bound levels
    q2 = 1.0 - alpha / 2
    return sim_stats.loc[sim_stats["quantile"] == q2]["value"].values[idx]

def get_lower_bound(sim_stats, alpha, idx): 
    # get lower bound levels
    q1 = alpha / 2.
    return sim_stats.loc[sim_stats["quantile"] == q1]["value"].values[idx]


def get_aggregate_wis(realdata, 
                      sim_stats, 
                      alphas=[0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90], 
                      aggr_fun=None, 
                      norm=False):
    wis = []
    for i in range(len(realdata)):
        wis.append(weighted_interval_score(
                            y=realdata[i], 
                            u_s=np.array([get_upper_bound(sim_stats, alpha=alpha, idx=i) for alpha in alphas]), 
                            l_s=np.array([get_lower_bound(sim_stats, alpha=alpha, idx=i) for alpha in alphas]), 
                            m=sim_stats.loc[sim_stats["quantile"] == 0.5]["value"].values[i],
                            alpha_ks=alphas, 
                            norm=norm))
    if aggr_fun != None:
        return aggr_fun(wis)
    else:
        return wis
        
def compute_dict_WIS_AE(df, alphas):
    if 'quantiles' in df.columns:
        df = df.rename(columns={"quantiles": "quantile"})
    realdata = df[df['quantile'] == 0.5]['hospitalizations'].values
    sim_stats = df.drop(columns=['date', 'hospitalizations', 'horizon'])
    wmape = get_wmape(realdata, sim_stats.loc[sim_stats["quantile"] == 0.5]["value"].values)
    wis_list = get_aggregate_wis(realdata, 
                      sim_stats, 
                      alphas=alphas, 
                      aggr_fun=None, 
                      norm=False)
    wis_mean = np.mean(wis_list)
    return wis_list, wis_mean, wmape

In [ ]:
adaptive_ensemble2_path = "../../output_data/adaptive_ensemble2_agestrata"
horizon_to_date = df_surv.set_index('horizon')['date'].to_dict()
surv_lookup = df_surv[['date', 'hospitalizations']].drop_duplicates()
k_values = [0.05, 0.15, 0.25, 0.50, 0.75]
alphas=[0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]


dict_k_wis_rounds = {}
dict_k_mae_rounds = {}
for k in k_values:
    dict_wis_rounds = {}
    dict_mae_rounds = {}
    unique_dates = df_surv['date'].sort_values().unique()[:-2]
    for date in unique_dates:
        # Adaptive Ensemble2
        print(date)
        full_path_adaptive_ensemble2 = f"{adaptive_ensemble2_path}/{date.strftime('%Y-%m-%d')}_{k}_{loss_function}.csv"
        print(full_path_adaptive_ensemble2)
        df_adaptive_ensemble2 = import_ensemble2(full_path_adaptive_ensemble2, surv_lookup, horizon_to_date)
        print(df_adaptive_ensemble2)
        wis_list_adens2, wis_mean_adens2, wmape_adens2 = compute_dict_WIS_AE(df_adaptive_ensemble2, alphas)
        
        # Original ensemble
        df_original_ensemble2 = import_ensemble_original(df_original_ensemble, df_surv, date)
        wis_list_original_ens2, wis_mean_original_ens2, wmape_original_ens2 = compute_dict_WIS_AE(df_original_ensemble2, alphas)
        # Store WIS and AE results
        dict_wis_rounds[date] = [wis_mean_adens2, wis_mean_original_ens2]
        dict_mae_rounds[date] = [wmape_adens2, wmape_original_ens2]
    k_perc = int(k * 100)
    dict_k_wis_rounds[k_perc] = dict_wis_rounds
    dict_k_mae_rounds[k_perc] = dict_mae_rounds

2024-11-23 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2024-11-23_0.05_wmape.csv
     quantile    value  horizon       date  hospitalizations
0       0.010  136.230        3 2024-12-07            3122.0
1       0.025  147.900        3 2024-12-07            3122.0
2       0.050  151.000        3 2024-12-07            3122.0
3       0.100  160.600        3 2024-12-07            3122.0
4       0.150  167.400        3 2024-12-07            3122.0
..        ...      ...      ...        ...               ...
547     0.850  558.600       26 2025-05-17             920.0
548     0.900  596.980       26 2025-05-17             920.0
549     0.950  657.580       26 2025-05-17             920.0
550     0.975  712.680       26 2025-05-17             920.0
551     0.990  743.476       26 2025-05-17             920.0

[552 rows x 5 columns]
2024-11-30 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2024-11-30_0.05_wmape.csv
     quantile    value  horizon       date  hospitalizations
0       0.010  190.150        4 2024-12-14            4529.0
1       0.025  195.900        4 2024-12-14            4529.0
2       0.050  206.000        4 2024-12-14            4529.0
3       0.100  214.000        4 2024-12-14            4529.0
4       0.150  223.000        4 2024-12-14            4529.0
..        ...      ...      ...        ...               ...
524     0.850  585.240       26 2025-05-17             920.0
525     0.900  623.060       26 2025-05-17             920.0
526     0.950  667.920       26 2025-05-17             920.0
527     0.975  705.140       26 2025-05-17             920.0
528     0.990  757.186       26 2025-05-17             920.0

[529 rows x 5 columns]
2024-12-07 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2024-12-07_0.05_wmape.csv
     quantile    value  horizon       date  hospitalizations
0       0.010  234.920        5 2024-12-21            7556.0
1       0.025  244.500        5 2024-12-21            7556.0
2       0.050  251.000        5 2024-12-21            7556.0
3       0.100  262.200        5 2024-12-21            7556.0
4       0.150  268.000        5 2024-12-21            7556.0
..        ...      ...      ...        ...               ...
501     0.850  586.880       26 2025-05-17             920.0
502     0.900  618.200       26 2025-05-17             920.0
503     0.950  660.140       26 2025-05-17             920.0
504     0.975  676.000       26 2025-05-17             920.0
505     0.990  740.976       26 2025-05-17             920.0

[506 rows x 5 columns]
2024-12-14 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2024-12-14_0.05_wmape.csv
     quantile    value  horizon       date  hospitalizations
0       0.010  253.680        6 2024-12-28           14858.0
1       0.025  261.800        6 2024-12-28           14858.0
2       0.050  270.800        6 2024-12-28           14858.0
3       0.100  285.000        6 2024-12-28           14858.0
4       0.150  296.000        6 2024-12-28           14858.0
..        ...      ...      ...        ...               ...
478     0.850  550.200       26 2025-05-17             920.0
479     0.900  597.420       26 2025-05-17             920.0
480     0.950  657.720       26 2025-05-17             920.0
481     0.975  708.840       26 2025-05-17             920.0
482     0.990  737.436       26 2025-05-17             920.0

[483 rows x 5 columns]
2024-12-21 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2024-12-21_0.05_wmape.csv
     quantile    value  horizon       date  hospitalizations
0       0.010  259.960        7 2025-01-04           21984.0
1       0.025  279.700        7 2025-01-04           21984.0
2       0.050  288.400        7 2025-01-04           21984.0
3       0.100  299.600        7 2025-01-04           21984.0
4       0.150  310.000        7 2025-01-04           21984.0
..        ...      ...      ...        ...               ...
455     0.850  544.780       26 2025-05-17             920.0
456     0.900  577.280       26 2025-05-17             920.0
457     0.950  631.780       26 2025-05-17             920.0
458     0.975  684.640       26 2025-05-17             920.0
459     0.990  723.574       26 2025-05-17             920.0

[460 rows x 5 columns]
2024-12-28 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2024-12-28_0.05_wmape.csv
     quantile    value  horizon       date  hospitalizations
0       0.010  242.690        8 2025-01-11           17210.0
1       0.025  257.800        8 2025-01-11           17210.0
2       0.050  263.800        8 2025-01-11           17210.0
3       0.100  280.000        8 2025-01-11           17210.0
4       0.150  295.000        8 2025-01-11           17210.0
..        ...      ...      ...        ...               ...
432     0.850  537.340       26 2025-05-17             920.0
433     0.900  567.660       26 2025-05-17             920.0
434     0.950  603.040       26 2025-05-17             920.0
435     0.975  653.840       26 2025-05-17             920.0
436     0.990  713.162       26 2025-05-17             920.0

[437 rows x 5 columns]
2025-01-04 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-01-04_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010   212.260000        9 2025-01-18           17547.0
1       0.025   224.600000        9 2025-01-18           17547.0
2       0.050   236.000000        9 2025-01-18           17547.0
3       0.100   248.200000        9 2025-01-18           17547.0
4       0.150   257.400000        9 2025-01-18           17547.0
..        ...          ...      ...        ...               ...
409     0.850   548.293259       26 2025-05-17             920.0
410     0.900   590.096339       26 2025-05-17             920.0
411     0.950   676.211735       26 2025-05-17             920.0
412     0.975  1398.600000       26 2025-05-17             920.0
413     0.990  1446.960000       26 2025-05-17             920.0

[414 rows x 5 columns]
2025-01-11 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-01-11_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010   173.380000       10 2025-01-25           21440.0
1       0.025   181.700000       10 2025-01-25           21440.0
2       0.050   195.800000       10 2025-01-25           21440.0
3       0.100   201.600000       10 2025-01-25           21440.0
4       0.150   211.000000       10 2025-01-25           21440.0
..        ...          ...      ...        ...               ...
386     0.850   538.678766       26 2025-05-17             920.0
387     0.900   580.054920       26 2025-05-17             920.0
388     0.950   678.950042       26 2025-05-17             920.0
389     0.975  1398.600000       26 2025-05-17             920.0
390     0.990  1446.960000       26 2025-05-17             920.0

[391 rows x 5 columns]
2025-01-18 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-01-18_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010   135.570000       11 2025-02-01           28006.0
1       0.025   140.900000       11 2025-02-01           28006.0
2       0.050   152.800000       11 2025-02-01           28006.0
3       0.100   168.600000       11 2025-02-01           28006.0
4       0.150   175.800000       11 2025-02-01           28006.0
..        ...          ...      ...        ...               ...
363     0.850   519.464757       26 2025-05-17             920.0
364     0.900   567.038346       26 2025-05-17             920.0
365     0.950   651.333940       26 2025-05-17             920.0
366     0.975   843.820000       26 2025-05-17             920.0
367     0.990  1425.876000       26 2025-05-17             920.0

[368 rows x 5 columns]
2025-01-25 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-01-25_0.05_wmape.csv
     quantile       value  horizon       date  hospitalizations
0       0.010  104.870000       12 2025-02-08           30194.0
1       0.025  114.700000       12 2025-02-08           30194.0
2       0.050  120.800000       12 2025-02-08           30194.0
3       0.100  125.600000       12 2025-02-08           30194.0
4       0.150  134.400000       12 2025-02-08           30194.0
..        ...         ...      ...        ...               ...
340     0.850  500.428341       26 2025-05-17             920.0
341     0.900  535.004327       26 2025-05-17             920.0
342     0.950  597.764012       26 2025-05-17             920.0
343     0.975  641.184245       26 2025-05-17             920.0
344     0.990  669.253643       26 2025-05-17             920.0

[345 rows x 5 columns]
2025-02-01 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-02-01_0.05_wmape.csv
     quantile       value  horizon       date  hospitalizations
0       0.010   75.500000       13 2025-02-15           26070.0
1       0.025   80.000000       13 2025-02-15           26070.0
2       0.050   88.800000       13 2025-02-15           26070.0
3       0.100  100.600000       13 2025-02-15           26070.0
4       0.150  106.000000       13 2025-02-15           26070.0
..        ...         ...      ...        ...               ...
317     0.850  497.746570       26 2025-05-17             920.0
318     0.900  535.007547       26 2025-05-17             920.0
319     0.950  586.975541       26 2025-05-17             920.0
320     0.975  634.979471       26 2025-05-17             920.0
321     0.990  669.253643       26 2025-05-17             920.0

[322 rows x 5 columns]
2025-02-08 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-02-08_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010    57.690000       14 2025-02-22           22122.0
1       0.025    60.000000       14 2025-02-22           22122.0
2       0.050    65.800000       14 2025-02-22           22122.0
3       0.100    71.600000       14 2025-02-22           22122.0
4       0.150    75.400000       14 2025-02-22           22122.0
..        ...          ...      ...        ...               ...
294     0.850   505.681680       26 2025-05-17             920.0
295     0.900   547.193480       26 2025-05-17             920.0
296     0.950   606.957221       26 2025-05-17             920.0
297     0.975   665.086194       26 2025-05-17             920.0
298     0.990  1118.052000       26 2025-05-17             920.0

[299 rows x 5 columns]
2025-02-15 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-02-15_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010    40.872500       15 2025-03-01           18115.0
1       0.025    42.000000       15 2025-03-01           18115.0
2       0.050    45.500000       15 2025-03-01           18115.0
3       0.100    48.600000       15 2025-03-01           18115.0
4       0.150    54.000000       15 2025-03-01           18115.0
..        ...          ...      ...        ...               ...
271     0.850   512.281001       26 2025-05-17             920.0
272     0.900   558.309710       26 2025-05-17             920.0
273     0.950   644.853283       26 2025-05-17             920.0
274     0.975   884.740000       26 2025-05-17             920.0
275     0.990  1257.756000       26 2025-05-17             920.0

[276 rows x 5 columns]
2025-02-22 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-02-22_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010    25.960000       16 2025-03-08           13926.0
1       0.025    29.700000       16 2025-03-08           13926.0
2       0.050    31.800000       16 2025-03-08           13926.0
3       0.100    37.600000       16 2025-03-08           13926.0
4       0.150    41.400000       16 2025-03-08           13926.0
..        ...          ...      ...        ...               ...
248     0.850   515.524747       26 2025-05-17             920.0
249     0.900   554.921715       26 2025-05-17             920.0
250     0.950   644.853283       26 2025-05-17             920.0
251     0.975   884.740000       26 2025-05-17             920.0
252     0.990  1257.756000       26 2025-05-17             920.0

[253 rows x 5 columns]
2025-03-01 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-03-01_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010    19.540000       17 2025-03-15           10519.0
1       0.025    22.000000       17 2025-03-15           10519.0
2       0.050    24.800000       17 2025-03-15           10519.0
3       0.100    26.500000       17 2025-03-15           10519.0
4       0.150    28.400000       17 2025-03-15           10519.0
..        ...          ...      ...        ...               ...
225     0.850   519.391568       26 2025-05-17             920.0
226     0.900   558.566149       26 2025-05-17             920.0
227     0.950   644.853283       26 2025-05-17             920.0
228     0.975   884.740000       26 2025-05-17             920.0
229     0.990  1257.756000       26 2025-05-17             920.0

[230 rows x 5 columns]
2025-03-08 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-03-08_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010     9.960000       18 2025-03-22            7858.0
1       0.025    13.900000       18 2025-03-22            7858.0
2       0.050    16.000000       18 2025-03-22            7858.0
3       0.100    19.600000       18 2025-03-22            7858.0
4       0.150    21.400000       18 2025-03-22            7858.0
..        ...          ...      ...        ...               ...
202     0.850   521.685389       26 2025-05-17             920.0
203     0.900   561.306160       26 2025-05-17             920.0
204     0.950   645.043408       26 2025-05-17             920.0
205     0.975   884.740000       26 2025-05-17             920.0
206     0.990  1257.756000       26 2025-05-17             920.0

[207 rows x 5 columns]
2025-03-15 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-03-15_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010     8.380000       19 2025-03-29            5265.0
1       0.025     9.000000       19 2025-03-29            5265.0
2       0.050    11.333333       19 2025-03-29            5265.0
3       0.100    14.000000       19 2025-03-29            5265.0
4       0.150    15.666667       19 2025-03-29            5265.0
..        ...          ...      ...        ...               ...
179     0.850   525.350644       26 2025-05-17             920.0
180     0.900   561.306160       26 2025-05-17             920.0
181     0.950   645.043408       26 2025-05-17             920.0
182     0.975   884.740000       26 2025-05-17             920.0
183     0.990  1257.756000       26 2025-05-17             920.0

[184 rows x 5 columns]
2025-03-22 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-03-22_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010     6.690000       20 2025-04-05            3561.0
1       0.025     7.900000       20 2025-04-05            3561.0
2       0.050     8.000000       20 2025-04-05            3561.0
3       0.100    10.000000       20 2025-04-05            3561.0
4       0.150    12.000000       20 2025-04-05            3561.0
..        ...          ...      ...        ...               ...
156     0.850   525.461304       26 2025-05-17             920.0
157     0.900   562.427701       26 2025-05-17             920.0
158     0.950   645.326097       26 2025-05-17             920.0
159     0.975   887.140000       26 2025-05-17             920.0
160     0.990  1257.756000       26 2025-05-17             920.0

[161 rows x 5 columns]
2025-03-29 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-03-29_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010     4.690000       21 2025-04-12            2457.0
1       0.025     6.000000       21 2025-04-12            2457.0
2       0.050     7.000000       21 2025-04-12            2457.0
3       0.100     9.250000       21 2025-04-12            2457.0
4       0.150    10.250000       21 2025-04-12            2457.0
..        ...          ...      ...        ...               ...
133     0.850   525.461304       26 2025-05-17             920.0
134     0.900   562.427701       26 2025-05-17             920.0
135     0.950   645.326097       26 2025-05-17             920.0
136     0.975   887.140000       26 2025-05-17             920.0
137     0.990  1257.756000       26 2025-05-17             920.0

[138 rows x 5 columns]
2025-04-05 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-04-05_0.05_wmape.csv
     quantile        value  horizon       date  hospitalizations
0       0.010     4.617500       22 2025-04-19            1853.0
1       0.025     5.333333       22 2025-04-19            1853.0
2       0.050     6.000000       22 2025-04-19            1853.0
3       0.100     7.000000       22 2025-04-19            1853.0
4       0.150     8.000000       22 2025-04-19            1853.0
..        ...          ...      ...        ...               ...
110     0.850   525.461304       26 2025-05-17             920.0
111     0.900   562.708039       26 2025-05-17             920.0
112     0.950   645.326097       26 2025-05-17             920.0
113     0.975   887.140000       26 2025-05-17             920.0
114     0.990  1257.756000       26 2025-05-17             920.0

[115 rows x 5 columns]
2025-04-12 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-04-12_0.05_wmape.csv
    quantile        value  horizon       date  hospitalizations
0      0.010     1.000000       23 2025-04-26            1527.0
1      0.025     2.000000       23 2025-04-26            1527.0
2      0.050     3.675000       23 2025-04-26            1527.0
3      0.100     4.750000       23 2025-04-26            1527.0
4      0.150     6.000000       23 2025-04-26            1527.0
..       ...          ...      ...        ...               ...
87     0.850   525.461304       26 2025-05-17             920.0
88     0.900   562.708039       26 2025-05-17             920.0
89     0.950   645.326097       26 2025-05-17             920.0
90     0.975   887.140000       26 2025-05-17             920.0
91     0.990  1257.756000       26 2025-05-17             920.0

[92 rows x 5 columns]
2025-04-19 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-04-19_0.05_wmape.csv
    quantile        value  horizon       date  hospitalizations
0      0.010     1.270000       24 2025-05-03            1180.0
1      0.025     2.000000       24 2025-05-03            1180.0
2      0.050     3.000000       24 2025-05-03            1180.0
3      0.100     4.000000       24 2025-05-03            1180.0
4      0.150     5.962500       24 2025-05-03            1180.0
..       ...          ...      ...        ...               ...
64     0.850   525.461304       26 2025-05-17             920.0
65     0.900   562.708039       26 2025-05-17             920.0
66     0.950   645.326097       26 2025-05-17             920.0
67     0.975   887.140000       26 2025-05-17             920.0
68     0.990  1257.756000       26 2025-05-17             920.0

[69 rows x 5 columns]
2025-04-26 00:00:00
../output_data/review_adaptive_ensemble2_agestrata/2025-04-26_0.05_wmape.csv
    quantile        value  horizon       date  hospitalizations
0      0.010     1.000000       25 2025-05-10             977.0
1      0.025     1.900000       25 2025-05-10             977.0
2      0.050     1.966667       25 2025-05-10             977.0
3      0.100     2.750000       25 2025-05-10             977.0
4      0.150     3.750000       25 2025-05-10             977.0

In [49]:
dict_k_wis_rounds

{5: {Timestamp('2024-11-23 00:00:00'): [7568.682239550814, 4768.647961047382],
  Timestamp('2024-11-30 00:00:00'): [7862.203933898624, 4941.808243615357],
  Timestamp('2024-12-07 00:00:00'): [8187.080566053404, 5125.126754179272],
  Timestamp('2024-12-14 00:00:00'): [8321.071203216265, 5311.092101823443],
  Timestamp('2024-12-21 00:00:00'): [7941.546491004112, 5495.633985718677],
  Timestamp('2024-12-28 00:00:00'): [7308.34519279938, 5652.07991668768],
  Timestamp('2025-01-04 00:00:00'): [6294.093737602216, 5672.449646767913],
  Timestamp('2025-01-11 00:00:00'): [4966.813811841505, 5498.506590581535],
  Timestamp('2025-01-18 00:00:00'): [5007.429738877248, 5485.334959436747],
  Timestamp('2025-01-25 00:00:00'): [4351.807519987544, 5453.397724080024],
  Timestamp('2025-02-01 00:00:00'): [3446.9214677310333, 5248.431186594242],
  Timestamp('2025-02-08 00:00:00'): [2529.8930620926044, 4695.813263385327],
  Timestamp('2025-02-15 00:00:00'): [1785.3539232503508, 3928.4593676640425],
  Timestamp('2025-02-22 00:00:00'): [1494.47056463537, 3259.638036940306],
  Timestamp('2025-03-01 00:00:00'): [1309.4652265798873, 2670.9919145885206],
  Timestamp('2025-03-08 00:00:00'): [1103.386551495209, 2168.7017739097487],
  Timestamp('2025-03-15 00:00:00'): [947.4969112431006, 1781.78861249517],
  Timestamp('2025-03-22 00:00:00'): [786.1508732736362, 1456.5275670078247],
  Timestamp('2025-03-29 00:00:00'): [696.1173877195911, 1149.633321057759],
  Timestamp('2025-04-05 00:00:00'): [635.137673433657, 928.839240603993],
  Timestamp('2025-04-12 00:00:00'): [591.2145139805742, 779.9447525017905],
  Timestamp('2025-04-19 00:00:00'): [536.4497313953223, 691.3652678680359],
  Timestamp('2025-04-26 00:00:00'): [501.4127390385645, 629.443205093012],
  Timestamp('2025-05-03 00:00:00'): [498.65614827263045, 564.5537722152656]},
 15: {Timestamp('2024-11-23 00:00:00'): [6621.004980275987, 4768.647961047382],
  Timestamp('2024-11-30 00:00:00'): [6858.707191418092, 4941.808243615357],
  Timestamp('2024-12-07 00:00:00'): [7285.851414749024, 5125.126754179272],
  Timestamp('2024-12-14 00:00:00'): [7714.341954719896, 5311.092101823443],
  Timestamp('2024-12-21 00:00:00'): [7607.174761279127, 5495.633985718677],
  Timestamp('2024-12-28 00:00:00'): [7084.0670876159365, 5652.07991668768],
  Timestamp('2025-01-04 00:00:00'): [6574.70909007934, 5672.449646767913],
  Timestamp('2025-01-11 00:00:00'): [5534.239096557176, 5498.506590581535],
  Timestamp('2025-01-18 00:00:00'): [5086.646965959647, 5485.334959436747],
  Timestamp('2025-01-25 00:00:00'): [4396.784975231892, 5453.397724080024],
  Timestamp('2025-02-01 00:00:00'): [3519.2970910021327, 5248.431186594242],
  Timestamp('2025-02-08 00:00:00'): [2565.333510831721, 4695.813263385327],
  Timestamp('2025-02-15 00:00:00'): [2004.549344567324, 3928.4593676640425],
  Timestamp('2025-02-22 00:00:00'): [1669.3174143609053, 3259.638036940306],
  Timestamp('2025-03-01 00:00:00'): [1398.2135523757834, 2670.9919145885206],
  Timestamp('2025-03-08 00:00:00'): [1193.282599456349, 2168.7017739097487],
  Timestamp('2025-03-15 00:00:00'): [963.7607900393725, 1781.78861249517],
  Timestamp('2025-03-22 00:00:00'): [806.7908019975876, 1456.5275670078247],
  Timestamp('2025-03-29 00:00:00'): [702.6946228549397, 1149.633321057759],
  Timestamp('2025-04-05 00:00:00'): [631.9483579405211, 928.839240603993],
  Timestamp('2025-04-12 00:00:00'): [581.2705581714819, 779.9447525017905],
  Timestamp('2025-04-19 00:00:00'): [517.404068737524, 691.3652678680359],
  Timestamp('2025-04-26 00:00:00'): [488.0383882705424, 629.443205093012],
  Timestamp('2025-05-03 00:00:00'): [486.8354612981097, 564.5537722152656]},
 25: {Timestamp('2024-11-23 00:00:00'): [6066.938746323575, 4768.647961047382],
  Timestamp('2024-11-30 00:00:00'): [6632.87992599655, 4941.808243615357],
  Timestamp('2024-12-07 00:00:00'): [7097.6163628561735, 5125.126754179272],
  Timestamp('2024-12-14 00:00:00'): [7321.106197846226, 5311.092101823443],
  Timestamp('2024-12-21 00:00:00'): [7179.88520724017, 5495.633985718677],
  Timestamp('2024-12-28 00:00:00'): [6788.940647575426, 5652.07991668768],
  Timestamp('2025-01-04 00:00:00'): [6315.1886594820035, 5672.449646767913],
  Timestamp('2025-01-11 00:00:00'): [5593.825342784032, 5498.506590581535],
  Timestamp('2025-01-18 00:00:00'): [5284.710927603504, 5485.334959436747],
  Timestamp('2025-01-25 00:00:00'): [4626.615971810626, 5453.397724080024],
  Timestamp('2025-02-01 00:00:00'): [3630.180376506658, 5248.431186594242],
  Timestamp('2025-02-08 00:00:00'): [2804.664174102149, 4695.813263385327],
  Timestamp('2025-02-15 00:00:00'): [2212.932136585718, 3928.4593676640425],
  Timestamp('2025-02-22 00:00:00'): [1730.797752855404, 3259.638036940306],
  Timestamp('2025-03-01 00:00:00'): [1438.8604336438075, 2670.9919145885206],
  Timestamp('2025-03-08 00:00:00'): [1203.9909186056204, 2168.7017739097487],
  Timestamp('2025-03-15 00:00:00'): [972.0794836285643, 1781.78861249517],
  Timestamp('2025-03-22 00:00:00'): [806.0308120766276, 1456.5275670078247],
  Timestamp('2025-03-29 00:00:00'): [687.4977013469053, 1149.633321057759],
  Timestamp('2025-04-05 00:00:00'): [617.7182059802486, 928.839240603993],
  Timestamp('2025-04-12 00:00:00'): [561.0171641326153, 779.9447525017905],
  Timestamp('2025-04-19 00:00:00'): [505.0199806926436, 691.3652678680359],
  Timestamp('2025-04-26 00:00:00'): [474.41716423781713, 629.443205093012],
  Timestamp('2025-05-03 00:00:00'): [474.2290123098609, 564.5537722152656]},
 50: {Timestamp('2024-11-23 00:00:00'): [5642.534749994312, 4768.647961047382],
  Timestamp('2024-11-30 00:00:00'): [5941.899073133269, 4941.808243615357],
  Timestamp('2024-12-07 00:00:00'): [6313.945862143886, 5125.126754179272],
  Timestamp('2024-12-14 00:00:00'): [6677.695905951722, 5311.092101823443],
  Timestamp('2024-12-21 00:00:00'): [6849.593455832454, 5495.633985718677],
  Timestamp('2024-12-28 00:00:00'): [6498.725420735427, 5652.07991668768],
  Timestamp('2025-01-04 00:00:00'): [6139.796099629511, 5672.449646767913],
  Timestamp('2025-01-11 00:00:00'): [5772.414453014986, 5498.506590581535],
  Timestamp('2025-01-18 00:00:00'): [5548.982991077408, 5485.334959436747],
  Timestamp('2025-01-25 00:00:00'): [4806.53260200301, 5453.397724080024],
  Timestamp('2025-02-01 00:00:00'): [3851.5219059122187, 5248.431186594242],
  Timestamp('2025-02-08 00:00:00'): [3115.997532810485, 4695.813263385327],
  Timestamp('2025-02-15 00:00:00'): [2469.8115423237564, 3928.4593676640425],
  Timestamp('2025-02-22 00:00:00'): [1976.9405444429658, 3259.638036940306],
  Timestamp('2025-03-01 00:00:00'): [1621.0882540472642, 2670.9919145885206],
  Timestamp('2025-03-08 00:00:00'): [1325.935234351659, 2168.7017739097487],
  Timestamp('2025-03-15 00:00:00'): [1052.2713597816498, 1781.78861249517],
  Timestamp('2025-03-22 00:00:00'): [863.3199648177952, 1456.5275670078247],
  Timestamp('2025-03-29 00:00:00'): [734.8513170799675, 1149.633321057759],
  Timestamp('2025-04-05 00:00:00'): [659.2055600335003, 928.839240603993],
  Timestamp('2025-04-12 00:00:00'): [606.0122769287477, 779.9447525017905],
  Timestamp('2025-04-19 00:00:00'): [544.5374429358683, 691.3652678680359],
  Timestamp('2025-04-26 00:00:00'): [510.88552933283245, 629.443205093012],
  Timestamp('2025-05-03 00:00:00'): [509.8994363181294, 564.5537722152656]},
 75: {Timestamp('2024-11-23 00:00:00'): [5464.063651448921, 4768.647961047382],
  Timestamp('2024-11-30 00:00:00'): [5697.979213239333, 4941.808243615357],
  Timestamp('2024-12-07 00:00:00'): [5909.102604845875, 5125.126754179272],
  Timestamp('2024-12-14 00:00:00'): [6135.516349574968, 5311.092101823443],
  Timestamp('2024-12-21 00:00:00'): [6220.793857669874, 5495.633985718677],
  Timestamp('2024-12-28 00:00:00'): [5997.868986551199, 5652.07991668768],
  Timestamp('2025-01-04 00:00:00'): [5897.256866762069, 5672.449646767913],
  Timestamp('2025-01-11 00:00:00'): [5745.73080077729, 5498.506590581535],
  Timestamp('2025-01-18 00:00:00'): [5493.448412239245, 5485.334959436747],
  Timestamp('2025-01-25 00:00:00'): [4843.494923513965, 5453.397724080024],
  Timestamp('2025-02-01 00:00:00'): [3982.8632651736457, 5248.431186594242],
  Timestamp('2025-02-08 00:00:00'): [3258.397795486369, 4695.813263385327],
  Timestamp('2025-02-15 00:00:00'): [2652.78239362505, 3928.4593676640425],
  Timestamp('2025-02-22 00:00:00'): [2140.201227029298, 3259.638036940306],
  Timestamp('2025-03-01 00:00:00'): [1743.2525707402415, 2670.9919145885206],
  Timestamp('2025-03-08 00:00:00'): [1424.7905098435706, 2168.7017739097487],
  Timestamp('2025-03-15 00:00:00'): [1122.0650112310918, 1781.78861249517],
  Timestamp('2025-03-22 00:00:00'): [907.1742408745232, 1456.5275670078247],
  Timestamp('2025-03-29 00:00:00'): [765.852349463364, 1149.633321057759],
  Timestamp('2025-04-05 00:00:00'): [684.5656109011924, 928.839240603993],
  Timestamp('2025-04-12 00:00:00'): [627.6898584601694, 779.9447525017905],
  Timestamp('2025-04-19 00:00:00'): [563.3323655689816, 691.3652678680359],
  Timestamp('2025-04-26 00:00:00'): [528.020949558665, 629.443205093012],
  Timestamp('2025-05-03 00:00:00'): [526.3448686973758, 564.5537722152656]}}

In [ ]:
# Create df_wis dataframe to store WIS results
rows = []

for k, group_data in dict_k_wis_rounds.items():
    for timestamp, values in group_data.items():
        rows.append({
            'k_perc': k,
            'week': timestamp,
            'wis_adaptive_ensemble2': values[0],
            'wis_original_ensemble2': values[1],
            'wis_rel_original2': values[0] / values[1],
        })
df_wis = pd.DataFrame(rows)
df_wis
df_wis.to_csv(f"../../output_data/performance_adaptive_agestrata/wis_performance_{loss_function}.csv", index=False)

In [ ]:
# Create df_mae dataframe to store MAE results
rows = []

for k, group_data in dict_k_mae_rounds.items():
    for timestamp, values in group_data.items():
        rows.append({
            'k_perc': k,
            'week': timestamp,
            'mae_adaptive_ensemble2': values[0],
            'mae_original_ensemble2': values[1],
            'mae_rel_original2': values[0] / values[1]
        })
df_mae = pd.DataFrame(rows)
df_mae.to_csv(f"../../output_data/performance_adaptive_agestrata/mae_performance_{loss_function}.csv", index=False)
df_mae

,k_perc,week,mae_adaptive_ensemble2,mae_original_ensemble2,mae_rel_original2
0,5,2024-11-23,0.893590,0.766121,1.166382
1,5,2024-11-30,0.801926,0.767795,1.044454
2,5,2024-12-07,0.804809,0.770324,1.044768
3,5,2024-12-14,0.799313,0.773769,1.033012
4,5,2024-12-21,0.788034,0.778749,1.011923
...,...,...,...,...,...
115,75,2025-04-05,0.926002,0.884763,1.046610
116,75,2025-04-12,0.944987,0.913165,1.034848
117,75,2025-04-19,0.956573,0.933324,1.024909
118,75,2025-04-26,0.964331,0.947473,1.017793
119,75,2025-05-03,0.970265,0.957476,1.013356