In [54]:
import pandas as pd 
import numpy as np
import requests
from io import StringIO
from datetime import timedelta, datetime
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [55]:
def read_csv_from_github(url):
    """
    Reads a CSV file from a given GitHub URL and returns it as a pandas DataFrame.
    input:
        url = URL of the CSV file on GitHub
    output:
        df = DataFrame containing the CSV data
    """
    response = requests.get(url)
    if response.status_code == 200:
        csv_content = response.content.decode('utf-8')
        return pd.read_csv(StringIO(csv_content))
    else:
        print(f"Failed to fetch file. Status code: {response.status_code}, Message: {response.text}")
        return pd.DataFrame()
        
def loading_surveillance_eval(start_date, github_repo, github_directory, surveillance_file, state, horizon_to_start):
    """
    This function loads the surveillance data from a GitHub repository.
    input:
        start_date = start date for the data
        github_repo = GitHub repository name
        github_directory = directory in the GitHub repository
        surveillance_file = name of the surveillance file
        state = state to filter the data
        horizon_to_start = horizon to start the data
    output:
        df_surv_date_US = dataframe with the filtered surveillance data
    """
    file_url = f"https://raw.githubusercontent.com/{github_repo}/main/{github_directory}/{surveillance_file}"
    df_surv = read_csv_from_github(file_url)
    start_date = pd.to_datetime(start_date)
    df_surv['date'] = pd.to_datetime(df_surv['date'])
    if state == 'all':
        df_surv_date_US = df_surv[(df_surv.date >= start_date)]
    else:
        df_surv_date_US = df_surv[(df_surv.location == state) & (df_surv.date >= start_date)]
    df_surv_date_US = df_surv_date_US.rename(columns={"value": "hospitalizations"})
    df_surv_date_US = df_surv_date_US.sort_values(by='date')
    df_surv_date_US['horizon'] = np.arange(1, len(df_surv_date_US)+1)
    if state == 'all':
        df_surv_date_US['horizon'] = df_surv_date_US.groupby('location').cumcount() + 1
    if 'X' in df_surv_date_US.columns:
        df_surv_date_US.drop(columns=['X'], inplace=True)
    df_surv_date_US = df_surv_date_US[df_surv_date_US['horizon'] >= horizon_to_start]
    df_surv_date_US['date'] = pd.to_datetime(df_surv_date_US['date'])
    return df_surv_date_US

In [56]:
state = 'US'
github_repo = "cdcepi/FluSight-forecast-hub"
github_directory = "auxiliary-data/target-data-archive"
# Loading surveillance data for evaluation: last surveillance file
start_date = datetime(2024, 11, 16)  # Adjusted to the latest date in the surveillance data
surveillance_file = "target-hospital-admissions_2025-06-14.csv"
horizon_to_start = 3
df_surv = loading_surveillance_eval(start_date, github_repo, github_directory, surveillance_file, state, horizon_to_start)
df_surv = df_surv.iloc[:-2]
df_surv['horizon'] = df_surv['horizon'] + 13
df_surv

           date location location_name  hospitalizations  weekly_rate  horizon
3888 2024-11-30       US            US            4261.0     1.272264       16
4638 2024-12-07       US            US            6271.0     1.872416       17
3889 2024-12-14       US            US            9131.0     2.726364       18
6956 2024-12-21       US            US           15374.0     4.590420       19
5735 2024-12-28       US            US           27597.0     8.240004       20
820  2025-01-04       US            US           38611.0    11.528600       21
1438 2025-01-11       US            US           30662.0     9.155162       22
6957 2025-01-18       US            US           32908.0     9.825780       23
5736 2025-01-25       US            US           40513.0    12.096506       24
9317 2025-02-01       US            US           51050.0    15.242678       25
5737 2025-02-08       US            US           54052.0    16.139025       26
5741 2025-02-15       US            US           46135.0    13.775141       27
5734 2025-02-22       US            US           37678.0    11.250022       28
9318 2025-03-01       US            US           30707.0     9.168598       29
3891 2025-03-08       US            US           23925.0     7.143606       30
8721 2025-03-15       US            US           18336.0     5.474824       31
9319 2025-03-22       US            US           13597.0     4.059837       32
2067 2025-03-29       US            US            9647.0     2.880433       33
8718 2025-04-05       US            US            6752.0     2.016035       34
4    2025-04-12       US            US            4867.0     1.453205       35
5740 2025-04-19       US            US            3814.0     1.138797       36
2068 2025-04-26       US            US            3235.0     0.965917       37
6961 2025-05-03       US            US            2441.0     0.728842       38
813  2025-05-10       US            US            2105.0     0.628518       39
10   2025-05-17       US            US            1793.0     0.535360       40
5729 2025-05-24       US            US            1665.0     0.497141       41
1442 2025-05-31       US            US            1740.0     0.519535       42

In [ ]:
loss_function = 'wmape'
season = "2024-2025"
df_original_ensemble = pd.read_csv(f'../../output_data/original_ensembles_bootstrap/original_scenarios_S2_bootstrap_US_{loss_function}_{season}_k_values.csv')
df_original_ensemble = df_original_ensemble[df_original_ensemble['scenario_id'] == 'Ens2']
df_original_ensemble

       quantile        value  horizon scenario_id  n_bootstrapping
57960     0.010    13.038024        1        Ens2                0
57961     0.025    15.281052        1        Ens2                0
57962     0.050    28.997489        1        Ens2                0
57963     0.100    78.671926        1        Ens2                0
57964     0.150    87.448307        1        Ens2                0
...         ...          ...      ...         ...              ...
67615     0.850   826.549149       42        Ens2                9
67616     0.900  1045.109598       42        Ens2                9
67617     0.950  3073.775000       42        Ens2                9
67618     0.975  3482.272500       42        Ens2                9
67619     0.990  3684.309000       42        Ens2                9

[9660 rows x 5 columns]

In [59]:
def import_ensemble_original(df, df_surv, date_ref):
    df_surv['date'] = pd.to_datetime(df_surv['date'])
    valid_horizons = df_surv['horizon'].unique()
    df = df[df['horizon'].isin(valid_horizons)]
    # Map each horizon to its corresponding date
    horizon_to_date = df_surv.set_index('horizon')['date'].to_dict()
    df['date'] = df['horizon'].map(horizon_to_date)
    # Filter to only include dates after or equal to date_only
    date_ref = pd.to_datetime(date_ref)
    df = df[df['date'] >= date_ref]
    # Merge in hospitalization targets
    df = df.merge(df_surv[['date', 'hospitalizations']].drop_duplicates(), on='date', how='left')
    return df

def import_ensemble2(file_path, surv_lookup, horizon_to_date):
    df = pd.read_csv(file_path, index_col=0)
    df['date'] = df['horizon'].map(horizon_to_date)
    df['date'] = pd.to_datetime(df['date'])
    return df.merge(surv_lookup, on='date', how='left')

In [60]:
def get_perc_error(actual, sim, last=4): 
    return 100 * np.mean(np.abs(actual[-last:] - sim[-last:]) / actual[-last:])

def get_wmape(actual, sim) -> float:
    return np.sum(np.abs(actual - sim)) / np.sum(np.abs(actual))

def diff(a, b, norm=False): 
    if norm:
        if a != 0:
            return (a - b) / a
        else: 
            return 0
    else:
        return (a - b)

def interval_score(y, u, l, alpha, norm=False): 
    return -diff(l, u, norm=norm) + 2 / alpha * -diff(y, l, norm=norm) * (y < l) + 2 / alpha * diff(y, u, norm=norm) * (y > u)
    

def weighted_interval_score(y, u_s, l_s, m, alpha_ks, w0=1./2., norm=False):
    K = len(alpha_ks)
    wks = np.array(alpha_ks) / 2.
    return 1. / (K + 1./2.) * (w0 * np.abs(diff(y, m, norm=norm)) + np.dot(wks, [interval_score(y, u, l, a_k, norm=norm) for u, l, a_k in zip(u_s, l_s, alpha_ks)]))


def get_upper_bound(sim_stats, alpha, idx): 
    # get upper bound levels
    q2 = 1.0 - alpha / 2
    return sim_stats.loc[sim_stats["quantile"] == q2]["value"].values[idx]

def get_lower_bound(sim_stats, alpha, idx): 
    # get lower bound levels
    q1 = alpha / 2.
    return sim_stats.loc[sim_stats["quantile"] == q1]["value"].values[idx]


def get_aggregate_wis(realdata, 
                      sim_stats, 
                      alphas=[0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90], 
                      aggr_fun=None, 
                      norm=False):
    wis = []
    for i in range(len(realdata)):
        wis.append(weighted_interval_score(
                            y=realdata[i], 
                            u_s=np.array([get_upper_bound(sim_stats, alpha=alpha, idx=i) for alpha in alphas]), 
                            l_s=np.array([get_lower_bound(sim_stats, alpha=alpha, idx=i) for alpha in alphas]), 
                            m=sim_stats.loc[sim_stats["quantile"] == 0.5]["value"].values[i],
                            alpha_ks=alphas, 
                            norm=norm))
    if aggr_fun != None:
        return aggr_fun(wis)
    else:
        return wis
        
def compute_dict_WIS_AE(df, alphas):
    if 'quantiles' in df.columns:
        df = df.rename(columns={"quantiles": "quantile"})
    realdata = df[df['quantile'] == 0.5]['hospitalizations'].values
    sim_stats = df.drop(columns=['date', 'hospitalizations', 'horizon'])
    wmape = get_wmape(realdata, sim_stats.loc[sim_stats["quantile"] == 0.5]["value"].values)
    wis_list = get_aggregate_wis(realdata, 
                      sim_stats, 
                      alphas=alphas, 
                      aggr_fun=None, 
                      norm=False)
    wis_mean = np.mean(wis_list)
    return wis_list, wis_mean, wmape

In [ ]:
adaptive_ensemble2_path = "../../output_data/adaptive_ensemble_bootstrap"
horizon_to_date = df_surv.set_index('horizon')['date'].to_dict()
surv_lookup = df_surv[['date', 'hospitalizations']].drop_duplicates()
k_values = [0.05, 0.15, 0.25, 0.50, 0.75]
alphas=[0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]

dict_k_wis_rounds_nbootstrap = {}
dict_k_mae_rounds_nbootstrap = {}

for n_bootstrap in df_original_ensemble.n_bootstrapping.unique():
    print('N bootstrap: ', n_bootstrap)
    dict_k_wis_rounds = {}
    dict_k_mae_rounds = {}
    for k in k_values:
        dict_wis_rounds = {}
        dict_mae_rounds = {}
        unique_dates = df_surv['date'].sort_values().unique()[:-1]
        for date in unique_dates:
            # Adaptive Ensemble2
            print(date)
            full_path_adaptive_ensemble2 = f"{adaptive_ensemble2_path}/{date.strftime('%Y-%m-%d')}_{k}_{loss_function}_{n_bootstrap}.csv"
            print(full_path_adaptive_ensemble2)
            df_adaptive_ensemble2 = import_ensemble2(full_path_adaptive_ensemble2, surv_lookup, horizon_to_date)
            print(df_adaptive_ensemble2)
            wis_list_adens2, wis_mean_adens2, wmape_adens2 = compute_dict_WIS_AE(df_adaptive_ensemble2, alphas)
            
            # Original ensemble
            df_original_ensemble_n = df_original_ensemble[df_original_ensemble['n_bootstrapping'] == n_bootstrap]
            df_original_ensemble2 = import_ensemble_original(df_original_ensemble_n, df_surv, date)
            wis_list_original_ens2, wis_mean_original_ens2, wmape_original_ens2 = compute_dict_WIS_AE(df_original_ensemble2, alphas)
            # Store WIS and AE results
            dict_wis_rounds[date] = [wis_mean_adens2, wis_mean_original_ens2]
            dict_mae_rounds[date] = [wmape_adens2, wmape_original_ens2]
        k_perc = int(k * 100)
        dict_k_wis_rounds[k_perc] = dict_wis_rounds
        dict_k_mae_rounds[k_perc] = dict_mae_rounds
    dict_k_wis_rounds_nbootstrap[n_bootstrap] = dict_k_wis_rounds
    dict_k_mae_rounds_nbootstrap[n_bootstrap] = dict_k_mae_rounds

N bootstrap:  0
2024-11-30 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2024-11-30_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  2403.516000       16 2024-11-30            4261.0
1       0.025  2898.036567       16 2024-11-30            4261.0
2       0.050  3250.024217       16 2024-11-30            4261.0
3       0.100  3753.946926       16 2024-11-30            4261.0
4       0.150  4030.485051       16 2024-11-30            4261.0
..        ...          ...      ...        ...               ...
616     0.850   867.380000       42 2025-05-31            1740.0
617     0.900  3885.240000       42 2025-05-31            1740.0
618     0.950  3957.900000       42 2025-05-31            1740.0
619     0.975  4164.415000       42 2025-05-31            1740.0
620     0.990  4254.234000       42 2025-05-31            1740.0

[621 rows x 5 columns]
2024-12-07 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2024-12-07_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  4124.776000       17 2024-12-07            6271.0
1       0.025  4507.560000       17 2024-12-07            6271.0
2       0.050  4803.085425       17 2024-12-07            6271.0
3       0.100  5185.057728       17 2024-12-07            6271.0
4       0.150  5553.936458       17 2024-12-07            6271.0
..        ...          ...      ...        ...               ...
593     0.850   872.180000       42 2025-05-31            1740.0
594     0.900  3885.240000       42 2025-05-31            1740.0
595     0.950  3957.900000       42 2025-05-31            1740.0
596     0.975  4164.415000       42 2025-05-31            1740.0
597     0.990  4254.234000       42 2025-05-31            1740.0

[598 rows x 5 columns]
2024-12-14 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2024-12-14_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  5311.661519       18 2024-12-14            9131.0
1       0.025  5625.368579       18 2024-12-14            9131.0
2       0.050  6582.249531       18 2024-12-14            9131.0
3       0.100  7583.908455       18 2024-12-14            9131.0
4       0.150  7914.867639       18 2024-12-14            9131.0
..        ...          ...      ...        ...               ...
570     0.850   822.057239       42 2025-05-31            1740.0
571     0.900  3885.240000       42 2025-05-31            1740.0
572     0.950  3957.900000       42 2025-05-31            1740.0
573     0.975  4164.415000       42 2025-05-31            1740.0
574     0.990  4254.234000       42 2025-05-31            1740.0

[575 rows x 5 columns]
2024-12-21 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2024-12-21_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  5312.840000       19 2024-12-21           15374.0
1       0.025  6430.985000       19 2024-12-21           15374.0
2       0.050  7789.157686       19 2024-12-21           15374.0
3       0.100  8826.942240       19 2024-12-21           15374.0
4       0.150  9230.407224       19 2024-12-21           15374.0
..        ...          ...      ...        ...               ...
547     0.850   755.940000       42 2025-05-31            1740.0
548     0.900  3885.240000       42 2025-05-31            1740.0
549     0.950  3957.900000       42 2025-05-31            1740.0
550     0.975  4164.415000       42 2025-05-31            1740.0
551     0.990  4254.234000       42 2025-05-31            1740.0

[552 rows x 5 columns]
2024-12-28 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2024-12-28_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  5997.086000       20 2024-12-28           27597.0
1       0.025  6965.843083       20 2024-12-28           27597.0
2       0.050  7326.517487       20 2024-12-28           27597.0
3       0.100  8214.509534       20 2024-12-28           27597.0
4       0.150  8679.465253       20 2024-12-28           27597.0
..        ...          ...      ...        ...               ...
524     0.850   872.180000       42 2025-05-31            1740.0
525     0.900  3885.240000       42 2025-05-31            1740.0
526     0.950  3957.900000       42 2025-05-31            1740.0
527     0.975  4164.415000       42 2025-05-31            1740.0
528     0.990  4254.234000       42 2025-05-31            1740.0

[529 rows x 5 columns]
2025-01-04 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-01-04_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  6110.864100       21 2025-01-04           38611.0
1       0.025  6168.520338       21 2025-01-04           38611.0
2       0.050  6538.071216       21 2025-01-04           38611.0
3       0.100  7236.365805       21 2025-01-04           38611.0
4       0.150  7928.818999       21 2025-01-04           38611.0
..        ...          ...      ...        ...               ...
501     0.850   760.172678       42 2025-05-31            1740.0
502     0.900  3885.240000       42 2025-05-31            1740.0
503     0.950  3957.900000       42 2025-05-31            1740.0
504     0.975  4164.415000       42 2025-05-31            1740.0
505     0.990  4254.234000       42 2025-05-31            1740.0

[506 rows x 5 columns]
2025-01-11 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-01-11_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  5347.726000       22 2025-01-11           30662.0
1       0.025  5399.220000       22 2025-01-11           30662.0
2       0.050  5966.580000       22 2025-01-11           30662.0
3       0.100  6692.980000       22 2025-01-11           30662.0
4       0.150  8618.030000       22 2025-01-11           30662.0
..        ...          ...      ...        ...               ...
478     0.850   760.620492       42 2025-05-31            1740.0
479     0.900  3813.420000       42 2025-05-31            1740.0
480     0.950  3957.900000       42 2025-05-31            1740.0
481     0.975  4164.415000       42 2025-05-31            1740.0
482     0.990  4254.234000       42 2025-05-31            1740.0

[483 rows x 5 columns]
2025-01-18 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-01-18_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  5150.820000       23 2025-01-18           32908.0
1       0.025  5261.125000       23 2025-01-18           32908.0
2       0.050  5990.460000       23 2025-01-18           32908.0
3       0.100  6754.400000       23 2025-01-18           32908.0
4       0.150  8705.190000       23 2025-01-18           32908.0
..        ...          ...      ...        ...               ...
455     0.850   791.344726       42 2025-05-31            1740.0
456     0.900  3638.700000       42 2025-05-31            1740.0
457     0.950  3924.830000       42 2025-05-31            1740.0
458     0.975  4164.415000       42 2025-05-31            1740.0
459     0.990  4254.234000       42 2025-05-31            1740.0

[460 rows x 5 columns]
2025-01-25 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-01-25_0.05_wmape_0.csv
     quantile       value  horizon       date  hospitalizations
0       0.010  5259.31200       24 2025-01-25           40513.0
1       0.025  5541.65500       24 2025-01-25           40513.0
2       0.050  6549.30000       24 2025-01-25           40513.0
3       0.100  8011.76000       24 2025-01-25           40513.0
4       0.150  8964.55000       24 2025-01-25           40513.0
..        ...         ...      ...        ...               ...
432     0.850   717.94551       42 2025-05-31            1740.0
433     0.900  3496.98000       42 2025-05-31            1740.0
434     0.950  3868.82000       42 2025-05-31            1740.0
435     0.975  4003.82500       42 2025-05-31            1740.0
436     0.990  4254.23400       42 2025-05-31            1740.0

[437 rows x 5 columns]
2025-02-01 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-02-01_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  6553.808000       25 2025-02-01           51050.0
1       0.025  6665.145000       25 2025-02-01           51050.0
2       0.050  7149.410000       25 2025-02-01           51050.0
3       0.100  8189.407045       25 2025-02-01           51050.0
4       0.150  8630.601629       25 2025-02-01           51050.0
..        ...          ...      ...        ...               ...
409     0.850   690.080000       42 2025-05-31            1740.0
410     0.900  3344.100000       42 2025-05-31            1740.0
411     0.950  3620.790000       42 2025-05-31            1740.0
412     0.975  3788.475000       42 2025-05-31            1740.0
413     0.990  3892.462000       42 2025-05-31            1740.0

[414 rows x 5 columns]
2025-02-08 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-02-08_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  7187.906000       26 2025-02-08           54052.0
1       0.025  7897.375000       26 2025-02-08           54052.0
2       0.050  8053.480000       26 2025-02-08           54052.0
3       0.100  8220.613796       26 2025-02-08           54052.0
4       0.150  8371.135523       26 2025-02-08           54052.0
..        ...          ...      ...        ...               ...
386     0.850   706.202434       42 2025-05-31            1740.0
387     0.900  3132.900000       42 2025-05-31            1740.0
388     0.950  3380.700000       42 2025-05-31            1740.0
389     0.975  3462.805000       42 2025-05-31            1740.0
390     0.990  3695.000000       42 2025-05-31            1740.0

[391 rows x 5 columns]
2025-02-15 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-02-15_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  6010.980000       27 2025-02-15           46135.0
1       0.025  6098.700000       27 2025-02-15           46135.0
2       0.050  6163.000000       27 2025-02-15           46135.0
3       0.100  6299.600000       27 2025-02-15           46135.0
4       0.150  7556.570000       27 2025-02-15           46135.0
..        ...          ...      ...        ...               ...
363     0.850   743.576855       42 2025-05-31            1740.0
364     0.900  3109.180000       42 2025-05-31            1740.0
365     0.950  3347.700000       42 2025-05-31            1740.0
366     0.975  3432.640000       42 2025-05-31            1740.0
367     0.990  3548.522000       42 2025-05-31            1740.0

[368 rows x 5 columns]
2025-02-22 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-02-22_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  4425.420000       28 2025-02-22           37678.0
1       0.025  4472.950000       28 2025-02-22           37678.0
2       0.050  4523.400000       28 2025-02-22           37678.0
3       0.100  4602.000000       28 2025-02-22           37678.0
4       0.150  7683.420000       28 2025-02-22           37678.0
..        ...          ...      ...        ...               ...
340     0.850   743.576855       42 2025-05-31            1740.0
341     0.900  3083.600000       42 2025-05-31            1740.0
342     0.950  3243.370000       42 2025-05-31            1740.0
343     0.975  3388.050000       42 2025-05-31            1740.0
344     0.990  3450.502000       42 2025-05-31            1740.0

[345 rows x 5 columns]
2025-03-01 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-03-01_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  3340.480000       29 2025-03-01           30707.0
1       0.025  3360.950000       29 2025-03-01           30707.0
2       0.050  3369.400000       29 2025-03-01           30707.0
3       0.100  3434.400000       29 2025-03-01           30707.0
4       0.150  7445.900000       29 2025-03-01           30707.0
..        ...          ...      ...        ...               ...
317     0.850   743.576855       42 2025-05-31            1740.0
318     0.900  3083.600000       42 2025-05-31            1740.0
319     0.950  3243.370000       42 2025-05-31            1740.0
320     0.975  3388.050000       42 2025-05-31            1740.0
321     0.990  3450.502000       42 2025-05-31            1740.0

[322 rows x 5 columns]
2025-03-08 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-03-08_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  2447.280000       30 2025-03-08           23925.0
1       0.025  2485.500000       30 2025-03-08           23925.0
2       0.050  2516.600000       30 2025-03-08           23925.0
3       0.100  2555.400000       30 2025-03-08           23925.0
4       0.150  5466.240000       30 2025-03-08           23925.0
..        ...          ...      ...        ...               ...
294     0.850   743.576855       42 2025-05-31            1740.0
295     0.900  3083.600000       42 2025-05-31            1740.0
296     0.950  3243.370000       42 2025-05-31            1740.0
297     0.975  3388.050000       42 2025-05-31            1740.0
298     0.990  3450.502000       42 2025-05-31            1740.0

[299 rows x 5 columns]
2025-03-15 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-03-15_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  1882.000000       31 2025-03-15           18336.0
1       0.025  1897.000000       31 2025-03-15           18336.0
2       0.050  1937.900000       31 2025-03-15           18336.0
3       0.100  1979.000000       31 2025-03-15           18336.0
4       0.150  3044.513452       31 2025-03-15           18336.0
..        ...          ...      ...        ...               ...
271     0.850   743.576855       42 2025-05-31            1740.0
272     0.900  3083.600000       42 2025-05-31            1740.0
273     0.950  3243.370000       42 2025-05-31            1740.0
274     0.975  3388.050000       42 2025-05-31            1740.0
275     0.990  3450.502000       42 2025-05-31            1740.0

[276 rows x 5 columns]
2025-03-22 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-03-22_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010  1365.589800       32 2025-03-22           13597.0
1       0.025  1441.505569       32 2025-03-22           13597.0
2       0.050  1460.620121       32 2025-03-22           13597.0
3       0.100  1500.611844       32 2025-03-22           13597.0
4       0.150  1535.233214       32 2025-03-22           13597.0
..        ...          ...      ...        ...               ...
248     0.850   743.576855       42 2025-05-31            1740.0
249     0.900  3083.600000       42 2025-05-31            1740.0
250     0.950  3243.370000       42 2025-05-31            1740.0
251     0.975  3388.050000       42 2025-05-31            1740.0
252     0.990  3450.502000       42 2025-05-31            1740.0

[253 rows x 5 columns]
2025-03-29 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-03-29_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010   574.177640       33 2025-03-29            9647.0
1       0.025   754.084743       33 2025-03-29            9647.0
2       0.050  1040.472327       33 2025-03-29            9647.0
3       0.100  1116.271928       33 2025-03-29            9647.0
4       0.150  1147.785918       33 2025-03-29            9647.0
..        ...          ...      ...        ...               ...
225     0.850   743.576855       42 2025-05-31            1740.0
226     0.900  3083.600000       42 2025-05-31            1740.0
227     0.950  3243.370000       42 2025-05-31            1740.0
228     0.975  3388.050000       42 2025-05-31            1740.0
229     0.990  3450.502000       42 2025-05-31            1740.0

[230 rows x 5 columns]
2025-04-05 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-04-05_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010   238.256277       34 2025-04-05            6752.0
1       0.025   310.264462       34 2025-04-05            6752.0
2       0.050   540.052979       34 2025-04-05            6752.0
3       0.100   849.715686       34 2025-04-05            6752.0
4       0.150   881.835339       34 2025-04-05            6752.0
..        ...          ...      ...        ...               ...
202     0.850   743.576855       42 2025-05-31            1740.0
203     0.900  3083.600000       42 2025-05-31            1740.0
204     0.950  3243.370000       42 2025-05-31            1740.0
205     0.975  3388.050000       42 2025-05-31            1740.0
206     0.990  3450.502000       42 2025-05-31            1740.0

[207 rows x 5 columns]
2025-04-12 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-04-12_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010   105.314430       35 2025-04-12            4867.0
1       0.025   144.846486       35 2025-04-12            4867.0
2       0.050   267.320119       35 2025-04-12            4867.0
3       0.100   586.980000       35 2025-04-12            4867.0
4       0.150   638.756152       35 2025-04-12            4867.0
..        ...          ...      ...        ...               ...
179     0.850   743.576855       42 2025-05-31            1740.0
180     0.900  3088.840000       42 2025-05-31            1740.0
181     0.950  3311.610000       42 2025-05-31            1740.0
182     0.975  3409.890000       42 2025-05-31            1740.0
183     0.990  3450.502000       42 2025-05-31            1740.0

[184 rows x 5 columns]
2025-04-19 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-04-19_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010    47.221040       36 2025-04-19            3814.0
1       0.025    68.974168       36 2025-04-19            3814.0
2       0.050   126.530566       36 2025-04-19            3814.0
3       0.100   409.540000       36 2025-04-19            3814.0
4       0.150   502.000000       36 2025-04-19            3814.0
..        ...          ...      ...        ...               ...
156     0.850   743.576855       42 2025-05-31            1740.0
157     0.900  3083.600000       42 2025-05-31            1740.0
158     0.950  3243.370000       42 2025-05-31            1740.0
159     0.975  3388.050000       42 2025-05-31            1740.0
160     0.990  3450.502000       42 2025-05-31            1740.0

[161 rows x 5 columns]
2025-04-26 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-04-26_0.05_wmape_0.csv
     quantile        value  horizon       date  hospitalizations
0       0.010    22.914775       37 2025-04-26            3235.0
1       0.025    37.196198       37 2025-04-26            3235.0
2       0.050    76.519541       37 2025-04-26            3235.0
3       0.100   323.700000       37 2025-04-26            3235.0
4       0.150   401.800000       37 2025-04-26            3235.0
..        ...          ...      ...        ...               ...
133     0.850   743.576855       42 2025-05-31            1740.0
134     0.900  3088.840000       42 2025-05-31            1740.0
135     0.950  3311.610000       42 2025-05-31            1740.0
136     0.975  3409.890000       42 2025-05-31            1740.0
137     0.990  3450.502000       42 2025-05-31            1740.0

[138 rows x 5 columns]
2025-05-03 00:00:00
../output_data/review_adaptive_ensemble_bootstrap/2025-05-03_0.05_wmape_0.csv

In [62]:
dict_k_wis_rounds_nbootstrap

{0: {5: {Timestamp('2024-11-30 00:00:00'): [7893.633820732624,
    8059.021097013888],
   Timestamp('2024-12-07 00:00:00'): [7993.346942886773, 8217.24843648712],
   Timestamp('2024-12-14 00:00:00'): [9138.842960966262, 8370.062533978758],
   Timestamp('2024-12-21 00:00:00'): [9365.900175143812, 8533.872453316377],
   Timestamp('2024-12-28 00:00:00'): [9995.0691794949, 8743.795070724873],
   Timestamp('2025-01-04 00:00:00'): [9225.46718197008, 8938.832174999454],
   Timestamp('2025-01-11 00:00:00'): [8764.519571641575, 8847.9558052144],
   Timestamp('2025-01-18 00:00:00'): [9071.698862567815, 8930.707549576666],
   Timestamp('2025-01-25 00:00:00'): [9075.851162754609, 8915.688888232493],
   Timestamp('2025-02-01 00:00:00'): [8573.421798567819, 8575.64623506543],
   Timestamp('2025-02-08 00:00:00'): [7291.6625394546545, 7667.202009497036],
   Timestamp('2025-02-15 00:00:00'): [5872.728738887064, 6356.631807832168],
   Timestamp('2025-02-22 00:00:00'): [4777.546193478656, 5222.838080252835],
   Timestamp('2025-03-01 00:00:00'): [3833.738846485849, 4268.4601181197295],
   Timestamp('2025-03-08 00:00:00'): [3022.0153670336244, 3399.268236578182],
   Timestamp('2025-03-15 00:00:00'): [2280.87559446453, 2673.821546155194],
   Timestamp('2025-03-22 00:00:00'): [1755.7375833714084, 2105.8047852120076],
   Timestamp('2025-03-29 00:00:00'): [1339.0931947502083, 1674.8431929066332],
   Timestamp('2025-04-05 00:00:00'): [1085.34254126441, 1373.4654413237092],
   Timestamp('2025-04-12 00:00:00'): [965.9527228933347, 1180.3548927643233],
   Timestamp('2025-04-19 00:00:00'): [927.1115937848753, 1068.505856237248],
   Timestamp('2025-04-26 00:00:00'): [885.9963569555798, 985.4794927131933],
   Timestamp('2025-05-03 00:00:00'): [834.2913965455591, 898.4576076713778],
   Timestamp('2025-05-10 00:00:00'): [817.4587207593959, 859.4871515746861],
   Timestamp('2025-05-17 00:00:00'): [812.7672022861287, 839.3829232045381],
   Timestamp('2025-05-24 00:00:00'): [854.4418200661803, 868.5625442106866]},
  15: {Timestamp('2024-11-30 00:00:00'): [7654.578642336128,
    8059.021097013888],
   Timestamp('2024-12-07 00:00:00'): [8062.146803511928, 8217.24843648712],
   Timestamp('2024-12-14 00:00:00'): [8401.103742293484, 8370.062533978758],
   Timestamp('2024-12-21 00:00:00'): [9209.9988131322, 8533.872453316377],
   Timestamp('2024-12-28 00:00:00'): [9776.038747353985, 8743.795070724873],
   Timestamp('2025-01-04 00:00:00'): [9658.964259651937, 8938.832174999454],
   Timestamp('2025-01-11 00:00:00'): [9098.606121686393, 8847.9558052144],
   Timestamp('2025-01-18 00:00:00'): [9276.270030521398, 8930.707549576666],
   Timestamp('2025-01-25 00:00:00'): [9326.873096013593, 8915.688888232493],
   Timestamp('2025-02-01 00:00:00'): [8927.395054552388, 8575.64623506543],
   Timestamp('2025-02-08 00:00:00'): [7706.9459870692, 7667.202009497036],
   Timestamp('2025-02-15 00:00:00'): [6171.485504223414, 6356.631807832168],
   Timestamp('2025-02-22 00:00:00'): [5043.477178661312, 5222.838080252835],
   Timestamp('2025-03-01 00:00:00'): [4119.173687800786, 4268.4601181197295],
   Timestamp('2025-03-08 00:00:00'): [3237.550104449626, 3399.268236578182],
   Timestamp('2025-03-15 00:00:00'): [2483.2956096723456, 2673.821546155194],
   Timestamp('2025-03-22 00:00:00'): [1881.369140128949, 2105.8047852120076],
   Timestamp('2025-03-29 00:00:00'): [1433.961131708712, 1674.8431929066332],
   Timestamp('2025-04-05 00:00:00'): [1157.3400680284585, 1373.4654413237092],
   Timestamp('2025-04-12 00:00:00'): [1005.1184957324259, 1180.3548927643233],
   Timestamp('2025-04-19 00:00:00'): [938.3557265867481, 1068.505856237248],
   Timestamp('2025-04-26 00:00:00'): [898.0708252634489, 985.4794927131933],
   Timestamp('2025-05-03 00:00:00'): [838.8673197593571, 898.4576076713778],
   Timestamp('2025-05-10 00:00:00'): [815.4324561394227, 859.4871515746861],
   Timestamp('2025-05-17 00:00:00'): [807.3721488202449, 839.3829232045381],
   Timestamp('2025-05-24 00:00:00'): [842.6953959189375, 868.5625442106866]},
  25: {Timestamp('2024-11-30 00:00:00'): [7653.995101754925,
    8059.021097013888],
   Timestamp('2024-12-07 00:00:00'): [8125.071559371821, 8217.24843648712],
   Timestamp('2024-12-14 00:00:00'): [8408.954782369732, 8370.062533978758],
   Timestamp('2024-12-21 00:00:00'): [8972.015534690838, 8533.872453316377],
   Timestamp('2024-12-28 00:00:00'): [9511.547941658353, 8743.795070724873],
   Timestamp('2025-01-04 00:00:00'): [9502.7612192922, 8938.832174999454],
   Timestamp('2025-01-11 00:00:00'): [9242.155578400067, 8847.9558052144],
   Timestamp('2025-01-18 00:00:00'): [9404.938327646449, 8930.707549576666],
   Timestamp('2025-01-25 00:00:00'): [9435.182862667394, 8915.688888232493],
   Timestamp('2025-02-01 00:00:00'): [9052.50383385206, 8575.64623506543],
   Timestamp('2025-02-08 00:00:00'): [7883.313123922393, 7667.202009497036],
   Timestamp('2025-02-15 00:00:00'): [6414.572859225116, 6356.631807832168],
   Timestamp('2025-02-22 00:00:00'): [5238.037028410813, 5222.838080252835],
   Timestamp('2025-03-01 00:00:00'): [4243.355178469523, 4268.4601181197295],
   Timestamp('2025-03-08 00:00:00'): [3339.0947660780284, 3399.268236578182],
   Timestamp('2025-03-15 00:00:00'): [2560.324055739609, 2673.821546155194],
   Timestamp('2025-03-22 00:00:00'): [1904.3026250702567, 2105.8047852120076],
   Timestamp('2025-03-29 00:00:00'): [1463.571472899528, 1674.8431929066332],
   Timestamp('2025-04-05 00:00:00'): [1168.5112100055999, 1373.4654413237092],
   Timestamp('2025-04-12 00:00:00'): [1013.3256761803276, 1180.3548927643233],
   Timestamp('2025-04-19 00:00:00'): [942.7515273391599, 1068.505856237248],
   Timestamp('2025-04-26 00:00:00'): [894.7548014747214, 985.4794927131933],
   Timestamp('2025-05-03 00:00:00'): [836.2407648327193, 898.4576076713778],
   Timestamp('2025-05-10 00:00:00'): [812.9591766423197, 859.4871515746861],
   Timestamp('2025-05-17 00:00:00'): [801.215976892685, 839.3829232045381],
   Timestamp('2025-05-24 00:00:00'): [832.7761230193279, 868.5625442106866]},
  50: {Timestamp('2024-11-30 00:00:00'): [7739.504837750945,
    8059.021097013888],
   Timestamp('2024-12-07 00:00:00'): [8008.72823973493, 8217.24843648712],
   Timestamp('2024-12-14 00:00:00'): [8351.250446480131, 8370.062533978758],
   Timestamp('2024-12-21 00:00:00'): [8688.550212176795, 8533.872453316377],
   Timestamp('2024-12-28 00:00:00'): [9022.877810511962, 8743.795070724873],
   Timestamp('2025-01-04 00:00:00'): [9287.104308617672, 8938.832174999454],
   Timestamp('2025-01-11 00:00:00'): [9192.189360947057, 8847.9558052144],
   Timestamp('2025-01-18 00:00:00'): [9418.107506446502, 8930.707549576666],
   Timestamp('2025-01-25 00:00:00'): [9513.90265241973, 8915.688888232493],
   Timestamp('2025-02-01 00:00:00'): [9224.243840663798, 8575.64623506543],
   Timestamp('2025-02-08 00:00:00'): [8149.349194909504, 7667.202009497036],
   Timestamp('2025-02-15 00:00:00'): [6656.381161422963, 6356.631807832168],
   Timestamp('2025-02-22 00:00:00'): [5411.999392160051, 5222.838080252835],
   Timestamp('2025-03-01 00:00:00'): [4360.392663095572, 4268.4601181197295],
   Timestamp('2025-03-08 00:00:00'): [3403.74146542801, 3399.268236578182],
   Timestamp('2025-03-15 00:00:00'): [2613.7428272904017, 2673.821546155194],
   Timestamp('2025-03-22 00:00:00'): [1983.5345402862122, 2105.8047852120076],
   Timestamp('2025-03-29 00:00:00'): [1521.5096335999565, 1674.8431929066332],
   Timestamp('2025-04-05 00:00:00'): [1217.1289051741815, 1373.4654413237092],
   Timestamp('2025-04-12 00:00:00'): [1046.4074912971396, 1180.3548927643233],
   Timestamp('2025-04-19 00:00:00'): [966.5995941242169, 1068.505856237248],
   Timestamp('2025-04-26 00:00:00'): [909.5962435579935, 985.4794927131933],
   Timestamp('2025-05-03 00:00:00'): [844.8010187991255, 898.4576076713778],
   Timestamp('2025-05-10 00:00:00'): [816.468315613803, 859.4871515746861],
   Timestamp('2025-05-17 00:00:00'): [801.6218920053284, 839.3829232045381],
   Timestamp('2025-05-24 00:00:00'): [828.4849478385602, 868.5625442106866]},
  75: {Timestamp('2024-11-30 00:00:00'): [7836.721668045423,
    8059.021097013888],
   Timestamp('2024-12-07 00:00:00'): [8041.516221888679, 8217.24843648712],
   Timestamp('2024-12-14 00:00:00'): [8247.67539000985, 8370.062533978758],
   Timestamp('2024-12-21 00:00:00'): [8515.861757875993, 8533.872453316377],
   Timestamp('2024-12-28 00:00:00'): [8836.78087301022, 8743.795070724873],
   Timestamp('2025-01-04 00:00:00'): [9005.11500753131, 8938.832174999454],
   Timestamp('2025-01-11 00:00:00'): [8933.323235793849, 8847.9558052144],
   Timestamp('2025-01-18 00:00:00'): [9098.249941727758, 8930.707549576666],
   Timestamp('2025-01-25 00:00:00'): [9199.72572952294, 8915.688888232493],
   Timestamp('2025-02-01 00:00:00'): [8900.657292994778, 8575.64623506543],
   Timestamp('2025-02-08 00:00:00'): [7917.506356886826, 7667.202009497036],
   Timestamp('2025-02-15 00:00:00'): [6528.82969422004, 6356.631807832168],
   Timestamp('2025-02-22 00:00:00'): [5320.973533095149, 5222.838080252835],
   Timestamp('2025-03-01 00:00:00'): [4301.487834179924, 4268.4601181197295],
   Timestamp('2025-03-08 00:00:00'): [3389.1971892617844, 3399.268236578182],
   Timestamp('2025-03-15 00:00:00'): [2638.477915492875, 2673.821546155194],
   Timestamp('2025-03-22 00:00:00'): [2038.8297816897027, 2105.8047852120076],
   Timestamp('2025-03-29 00:00:00'): [1600.038673973774, 1674.8431929066332],
   Timestamp('2025-04-05 00:00:00'): [1297.773879469704, 1373.4654413237092],
   Timestamp('2025-04-12 00:00:00'): [1116.3480596866982, 1180.3548927643233],
   Timestamp('2025-04-19 00:00:00'): [1016.8082773899907, 1068.505856237248],
   Timestamp('2025-04-26 00:00:00'): [946.2910754209834, 985.4794927131933],
   Timestamp('2025-05-03 00:00:00'): [865.6415172354307, 898.4576076713778],
   Timestamp('2025-05-10 00:00:00'): [831.802828335628, 859.4871515746861],
   Timestamp('2025-05-17 00:00:00'): [813.7503360966766, 839.3829232045381],
   Timestamp('2025-05-24 00:00:00'): [838.8697110715264, 868.5625442106866]}},
 1: {5: {Timestamp('2024-11-30 00:00:00'): [7957.35483936104,
    8114.399937966489],
   Timestamp('2024-12-07 00:00:00'): [8287.662267051253, 8279.453009720228],
   Timestamp('2024-12-14 00:00:00'): [8376.982195838327, 8439.093926341184],
   Timestamp('2024-12-21 00:00:00'): [9247.178143197792, 8609.017500473683],
   Timestamp('2024-12-28 00:00:00'): [10184.993271595557, 8825.861308074846],
   Timestamp('2025-01-04 00:00:00'): [9460.557492910028, 9024.336979168684],
   Timestamp('2025-01-11 00:00:00'): [8819.494533304582, 8928.071508551504],
   Timestamp('2025-01-18 00:00:00'): [8983.339825975505, 9007.000624074062],
   Timestamp('2025-01-25 00:00:00'): [8952.623071622364, 8983.248132946683],
   Timestamp('2025-02-01 00:00:00'): [8470.751110631669, 8632.029990253486],
   Timestamp('2025-02-08 00:00:00'): [7232.962061878986, 7704.57917885195],
   Timestamp('2025-02-15 00:00:00'): [5918.511904432191, 6375.412951941631],
   Timestamp('2025-02-22 00:00:00'): [4812.5243442957235, 5226.026377071864],
   Timestamp('2025-03-01 00:00:00'): [3968.432826707979, 4261.359700241849],
   Timestamp('2025-03-08 00:00:00'): [3078.1102678502157, 3395.2296930442703],
   Timestamp('2025-03-15 00:00:00'): [2400.3454724958224, 2673.7265745745376],
   Timestamp('2025-03-22 00:00:00'): [1832.8215491715491, 2105.6137184377626],
   Timestamp('2025-03-29 00:00:00'): [1418.1971838060658, 1675.6010844737332],
   Timestamp('2025-04-05 00:00:00'): [1148.3321356178903, 1371.379632567793],
   Timestamp('2025-04-12 00:00:00'): [1004.0368302927617, 1180.3714780111031],
   Timestamp('2025-04-19 00:00:00'): [939.8191671449814, 1068.1279885034708],
   Timestamp('2025-04-26 00:00:00'): [890.598886638169, 985.3619416854748],
   Timestamp('2025-05-03 00:00:00'): [833.8077287028316, 897.7758007960268],
   Timestamp('2025-05-10 00:00:00'): [812.5777518181376, 858.6137769465868],
   Timestamp('2025-05-17 00:00:00'): [806.0424317221672, 836.6624553662656],
   Timestamp('2025-05-24 00:00:00'): [839.7750059020264, 863.2133559211354]},
  15: {Timestamp('2024-11-30 00:00:00'): [7785.304931433606,
    8114.399937966489],
   Timestamp('2024-12-07 00:00:00'): [7939.641672303226, 8279.453009720228],
   Timestamp('2024-12-14 00:00:00'): [8321.913483129938, 8439.093926341184],
   Timestamp('2024-12-21 00:00:00'): [9035.96215740301, 8609.017500473683],
   Timestamp('2024-12-28 00:00:00'): [9685.143081092723, 8825.861308074846],
   Timestamp('2025-01-04 00:00:00'): [9600.758275722312, 9024.336979168684],
   Timestamp('2025-01-11 00:00:00'): [9118.219669767794, 8928.071508551504],
   Timestamp('2025-01-18 00:00:00'): [9345.954483545956, 9007.000624074062],
   Timestamp('2025-01-25 00:00:00'): [9279.095367450727, 8983.248132946683],
   Timestamp('2025-02-01 00:00:00'): [8805.834440315251, 8632.029990253486],
   Timestamp('2025-02-08 00:00:00'): [7627.790258994739, 7704.57917885195],
   Timestamp('2025-02-15 00:00:00'): [6119.861037711071, 6375.412951941631],
   Timestamp('2025-02-22 00:00:00'): [5026.722120403897, 5226.026377071864],
   Timestamp('2025-03-01 00:00:00'): [4145.552749864736, 4261.359700241849],
   Timestamp('2025-03-08 00:00:00'): [3217.922517682436, 3395.2296930442703],
   Timestamp('2025-03-15 00:00:00'): [2449.891040460543, 2673.7265745745376],
   Timestamp('2025-03-22 00:00:00'): [1846.5889905657496, 2105.6137184377626],
   Timestamp('2025-03-29 00:00:00'): [1420.9482822503453, 1675.6010844737332],
   Timestamp('2025-04-05 00:00:00'): [1149.6904820206828, 1371.379632567793],
   Timestamp('2025-04-12 00:00:00'): [1003.7868185190282, 1180.3714780111031],
   Timestamp('2025-04-19 00:00:00'): [937.0822938744335, 1068.1279885034708],
   Timestamp('2025-04-26 00:00:00'): [891.5268878526299, 985.3619416854748],
   Timestamp('2025-05-03 00:00:00'): [828.4321567038751, 897.7758007960268],
   Timestamp('2025-05-10 00:00:00'): [805.8114929130265, 858.6137769465868],
   Timestamp('2025-05-17 00:00:00'): [794.3972446853186, 836.6624553662656],
   Timestamp('2025-05-24 00:00:00'): [820.8838854796513, 863.2133559211354]},
  25: {Timestamp('2024-11-30 00:00:00'): [7730.601186120119,
    8114.399937966489],
   Timestamp('2024-12-07 00:00:00'): [8147.037329129442, 8279.453009720228],
   Timestamp('2024-12-14 00:00:00'): [8455.027903423452, 8439.093926341184],
   Timestamp('2024-12-21 00:00:00'): [8878.105866786398, 8609.017500473683],
   Timestamp('2024-12-28 00:00:00'): [9466.386483587718, 8825.861308074846],
   Timestamp('2025-01-04 00:00:00'): [9460.347200694163, 9024.336979168684],
   Timestamp('2025-01-11 00:00:00'): [9265.189309770267, 8928.071508551504],
   Timestamp('2025-01-18 00:00:00'): [9371.01043571279, 9007.000624074062],
   Timestamp('2025-01-25 00:00:00'): [9418.443310753644, 8983.248132946683],
   Timestamp('2025-02-01 00:00:00'): [9054.911381579159, 8632.029990253486],
   Timestamp('2025-02-08 00:00:00'): [7784.324771553911, 7704.57917885195],
   Timestamp('2025-02-15 00:00:00'): [6331.678930253233, 6375.412951941631],
   Timestamp('2025-02-22 00:00:00'): [5142.620378625992, 5226.026377071864],
   Timestamp('2025-03-01 00:00:00'): [4186.287810633469, 4261.359700241849],
   Timestamp('2025-03-08 00:00:00'): [3307.3411920089557, 3395.2296930442703],
   Timestamp('2025-03-15 00:00:00'): [2541.1532110548196, 2673.7265745745376],
   Timestamp('2025-03-22 00:00:00'): [1895.7446684920508, 2105.6137184377626],
   Timestamp('2025-03-29 00:00:00'): [1445.1411367952826, 1675.6010844737332],
   Timestamp('2025-04-05 00:00:00'): [1156.0270057465104, 1371.379632567793],
   Timestamp('2025-04-12 00:00:00'): [999.3599662757808, 1180.3714780111031],
   Timestamp('2025-04-19 00:00:00'): [928.6877541115151, 1068.1279885034708],
   Timestamp('2025-04-26 00:00:00'): [882.8684831453571, 985.3619416854748],
   Timestamp('2025-05-03 00:00:00'): [826.8323796799912, 897.7758007960268],
   Timestamp('2025-05-10 00:00:00'): [803.4687788334726, 858.6137769465868],
   Timestamp('2025-05-17 00:00:00'): [791.4524323088335, 836.6624553662656],
   Timestamp('2025-05-24 00:00:00'): [818.2631572352701, 863.2133559211354]},
  50: {Timestamp('2024-11-30 00:00:00'): [7766.30299641341, 8114.399937966489],
   Timestamp('2024-12-07 00:00:00'): [8021.684681056631, 8279.453009720228],
   Timestamp('2024-12-14 00:00:00'): [8383.889619297128, 8439.093926341184],
   Timestamp('2024-12-21 00:00:00'): [8741.397828059713, 8609.017500473683],
   Timestamp('2024-12-28 00:00:00'): [9121.832369878362, 8825.861308074846],
   Timestamp('2025-01-04 00:00:00'): [9318.547100730415, 9024.336979168684],
   Timestamp('2025-01-11 00:00:00'): [9234.14569602229, 8928.071508551504],
   Timestamp('2025-01-18 00:00:00'): [9382.93649892825, 9007.000624074062],
   Timestamp('2025-01-25 00:00:00'): [9490.286568851518, 8983.248132946683],
   Timestamp('2025-02-01 00:00:00'): [9181.615594809877, 8632.029990253486],
   Timestamp('2025-02-08 00:00:00'): [8063.959517594557, 7704.57917885195],
   Timestamp('2025-02-15 00:00:00'): [6563.330848486685, 6375.412951941631],
   Timestamp('2025-02-22 00:00:00'): [5370.190425564549, 5226.026377071864],
   Timestamp('2025-03-01 00:00:00'): [4293.173840404213, 4261.359700241849],
   Timestamp('2025-03-08 00:00:00'): [3339.82869613794, 3395.2296930442703],
   Timestamp('2025-03-15 00:00:00'): [2566.5405084390836, 2673.7265745745376],
   Timestamp('2025-03-22 00:00:00'): [1939.692090767213, 2105.6137184377626],
   Timestamp('2025-03-29 00:00:00'): [1489.2907303810848, 1675.6010844737332],
   Timestamp('2025-04-05 00:00:00'): [1193.8285666314314, 1371.379632567793],
   Timestamp('2025-04-12 00:00:00'): [1030.9438655386296, 1180.3714780111031],
   Timestamp('2025-04-19 00:00:00'): [949.6992397853425, 1068.1279885034708],
   Timestamp('2025-04-26 00:00:00'): [897.7119083110689, 985.3619416854748],
   Timestamp('2025-05-03 00:00:00'): [833.4745150786621, 897.7758007960268],
   Timestamp('2025-05-10 00:00:00'): [806.6802724596926, 858.6137769465868],
   Timestamp('2025-05-17 00:00:00'): [791.8110845917104, 836.6624553662656],
   Timestamp('2025-05-24 00:00:00'): [818.378757589867, 863.2133559211354]},
  75: {Timestamp('2024-11-30 00:00:00'): [7933.083183988441,
    8114.399937966489],
   Timestamp('2024-12-07 00:00:00'): [8143.240925915141, 8279.453009720228],
   Timestamp('2024-12-14 00:00:00'): [8342.104969506781, 8439.093926341184],
   Timestamp('2024-12-21 00:00:00'): [8608.429644253692, 8609.017500473683],
   Timestamp('2024-12-28 00:00:00'): [8890.670344895054, 8825.861308074846],
   Timestamp('2025-01-04 00:00:00'): [9073.429582069422, 9024.336979168684],
   Timestamp('2025-01-11 00:00:00'): [8964.029908199202, 8928.071508551504],
   Timestamp('2025-01-18 00:00:00'): [9128.896056906075, 9007.000624074062],
   Timestamp('2025-01-25 00:00:00'): [9173.997980737824, 8983.248132946683],
   Timestamp('2025-02-01 00:00:00'): [8834.636524849373, 8632.029990253486],
   Timestamp('2025-02-08 00:00:00'): [7861.176847752917, 7704.57917885195],
   Timestamp('2025-02-15 00:00:00'): [6474.26063232583, 6375.412951941631],
   Timestamp('2025-02-22 00:00:00'): [5270.503739713798, 5226.026377071864],
   Timestamp('2025-03-01 00:00:00'): [4264.528604819881, 4261.359700241849],
   Timestamp('2025-03-08 00:00:00'): [3356.8810474654156, 3395.2296930442703],
   Timestamp('2025-03-15 00:00:00'): [2609.840605737133, 2673.7265745745376],
   Timestamp('2025-03-22 00:00:00'): [2019.3508662810452, 2105.6137184377626],
   Timestamp('2025-03-29 00:00:00'): [1581.4275941019507, 1675.6010844737332],
   Timestamp('2025-04-05 00:00:00'): [1283.0777058285357, 1371.379632567793],
   Timestamp('2025-04-12 00:00:00'): [1103.1269219664086, 1180.3714780111031],
   Timestamp('2025-04-19 00:00:00'): [1006.8059568234415, 1068.1279885034708],
   Timestamp('2025-04-26 00:00:00'): [936.4745612078387, 985.3619416854748],
   Timestamp('2025-05-03 00:00:00'): [857.0826834222871, 897.7758007960268],
   Timestamp('2025-05-10 00:00:00'): [823.3231165840926, 858.6137769465868],

In [ ]:
# Create df_wis dataframe to store WIS results
rows = []
for n, n_grouped_data in dict_k_wis_rounds_nbootstrap.items():
    for k, group_data in n_grouped_data.items():
        for timestamp, values in group_data.items():
            rows.append({
                'n_bootstrap': n,
                'k_perc': k,
                'week': timestamp,
                'wis_adaptive_ensemble2': values[0],
                'wis_original_ensemble2': values[1],
                'wis_rel_original2': values[0] / values[1],
            })
df_wis = pd.DataFrame(rows)
df_wis
df_wis.to_csv(f"../../output_data/performance_evaluation_bootstrap/wis_performance_{loss_function}.csv", index=False)

In [ ]:
# Create df_mae dataframe to store MAE results
rows = []
for n, n_grouped_data in dict_k_mae_rounds_nbootstrap.items():
    for k, group_data in n_grouped_data.items():
        for timestamp, values in group_data.items():
            rows.append({
                'n_bootstrap': n,
                'k_perc': k,
                'week': timestamp,
                'mae_adaptive_ensemble2': values[0],
                'mae_original_ensemble2': values[1],
                'mae_rel_original2': values[0] / values[1]
            })
df_mae = pd.DataFrame(rows)
df_mae.to_csv(f"../../output_data/performance_evaluation_bootstrap/mae_performance_{loss_function}.csv", index=False)
df_mae

,n_bootstrap,k_perc,week,mae_adaptive_ensemble2,mae_original_ensemble2,mae_rel_original2
0,0,5,2024-11-30,0.585630,0.638259,0.917542
1,0,5,2024-12-07,0.587728,0.633404,0.927888
2,0,5,2024-12-14,0.607131,0.630741,0.962567
3,0,5,2024-12-21,0.609220,0.632029,0.963912
4,0,5,2024-12-28,0.625568,0.648225,0.965048
...,...,...,...,...,...,...
1295,9,75,2025-04-26,0.747595,0.751716,0.994518
1296,9,75,2025-05-03,0.753228,0.754769,0.997959
1297,9,75,2025-05-10,0.764341,0.764355,0.999982
1298,9,75,2025-05-17,0.783871,0.781760,1.002700
1299,9,75,2025-05-24,0.820335,0.819046,1.001574